// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

console.log("AOC: day01");

var fileInput = "src/day01/input1.text";

var data = Fs.readFileSync(fileInput, "utf8").split("\n");

var values = data.map(function (line) {
      var first = line.split("").find(function (v) {
            return !Number.isNaN(Number(v));
          });
      var last = Belt_Array.reverse(line.split("")).find(function (v) {
            return !Number.isNaN(Number(v));
          });
      return Number(String(first === undefined ? undefined : Caml_option.some(first)) + String(last === undefined ? undefined : Caml_option.some(last)));
    });

var sum = Belt_Array.reduce(Belt_Array.map(values, (function (i) {
            if (Number.isNaN(i)) {
              return 0.0;
            } else {
              return i;
            }
          })), 0.0, (function (a, c) {
        return a + c;
      }));

console.log(sum);

var exampleInput = "src/day01/example1.text";

exports.fileInput = fileInput;
exports.exampleInput = exampleInput;
exports.data = data;
exports.values = values;
exports.sum = sum;
/*  Not a pure module */
